DX-887 DX-887 Move branch check to prepare-commit-msg

diff --git a/.githooks/prepare-commit-msg b/.githooks/prepare-commit-msg
--- a/.githooks/prepare-commit-msg
+++ b/.githooks/prepare-commit-msg
@@ -12,7 +12,22 @@ SHA1=$3
 # the number. This is to support release branches.
 valid_branch_regex="^(hotfix|feature|release|bugfix)\/([a-zA-Z]+\-[0-9]+|[0-9]\..*).*"
 branch_name="$(git rev-parse --abbrev-ref HEAD)"
-[[ $branch_name =~ $valid_branch_regex ]]
+
+if [[ ! $branch_name =~ $valid_branch_regex ]]
+then
+    echo "Commit error!"
+    echo "The branch '$branch_name' is not named according to our standards."
+    echo ""
+    echo "Expected format:"
+    echo "  $valid_branch_regex"
+    echo ""
+    echo "Examples:"
+    echo "  feature/dx-839_some_great_description"
+    echo "  release/1.8.1"
+    echo "  hotfix/dx-123_very_hot_fix"
+    exit 1
+fi
+
 task_id=${BASH_REMATCH[2]}
 
 echo "$task_id"' '$(cat "$COMMIT_MSG_FILE") > "$COMMIT_MSG_FILE"
